#name of the directory
DIR = app_e
ROOTDIR = ../..
OBJECTS = fixtext.o lentext.o deltext.o person.o
EXECS = test testpack

include $(ROOTDIR)/default.mk


test: fixtext.o lentext.o deltext.o test.o person.o
