#name of the directory
DIR = app_e
ROOTDIR = ../..
OBJECTS = fixtext.o lentext.o deltext.o person.o
EXECS = test.exe testpack.exe

include $(ROOTDIR)/default.mk


test.exe: fixtext.o lentext.o deltext.o test.o person.o
