#name of the directory
DIR = app_g
ROOTDIR = ../..
LIB = libindex.a
OBJECTS = recordng.o textind.o tindbuff.o strclass.o
EXECS = makerec mkindf tstind
LIBS = -liobuf

include $(ROOTDIR)/default.mk

recordng.o: recordng.h 

strclass.o: strclass.h 
